import Nav from "@/components/Nav";
import "./globals.css";
import { Roboto_Slab } from "next/font/google";
import Footer from "@/components/Footer";

const roboto = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <Nav />
                {children}
                <Footer />
            </body>
        </html>
    );
}
